### PR TITLE
Port for compatibility with Visual Studio 2013

### PR DESCRIPTION
**Pull request by weltling**
Only some minor changes was needed, now it is usable with VS2013.

Thanks.

### CODE REVIEW

**Comment by lemire** [comment]
Looks good.

**Comment by lemire** [comment]
I have included you as one of the collaborators of this project.

**Comment by weltling** [comment]
@lemire thanks for checking this. I'm putting most of my efforts into the PHP project, however the technology you use is pretty much exciting. Especially as there's no inline ASM. Despite of the learning fun, I'm also looking for the ways to improve PHP, so I landed here :)

The current PHP aims SSE2 as default, but also still C89. On windows, that's also about supporting an older compiler like VS2012. What do you think about making simdcomp C89 compatible?

Cheers.

**Comment by lemire** [comment]
C89 compatibility is a fine goal and maybe not difficult to achieve here. One probably wants to  have fallback defines for uint32_t. It just gets a bit uglier, but with good testing, it should be no problem.

**Comment by weltling** [comment]
Great, I'll be doing that. Will put a PR once it's done. 

Thanks.

**Comment by lemire** [comment]
Excellent.

**Pull request merged**
